language: generic 
sudo: required
services:
   - docker

before_install:
  - docker build -t frontend-docker -f Dockerfile.dev .

script:  
  - docker run -e CI=true frontend-docker npm run test -- --coverage