language: generic 
sudo: required
services:
   - docker

before_install:
  - docker build -t docker-frontend -f Dockerfile.dev .

script:  
  - docker run -e CI=true docker-frontend npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-frontend"
  env: "Dockerfrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-551438962807"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key